Parameters:
  PJPrefix:
    Type: String
  
  #InternetALB
  ALBName:
    Type: String
    Default: "lecture10-clf"

  IpAddressType:
    Type: String
    Default: "ipv4"

Resources:

  #=================================
  # ターゲットグループの作成
  #=================================       
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ALBName}-tg
      Tags:
        - Key: Name
          Value: !Sub ${ALBName}-tg
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: '200'
      VpcId: !ImportValue lecture10-clf-VPCid
      TargetType: instance
      Targets:
        - Id: !ImportValue Lecture10-EC2clf

  #=================================
  # ALBの作成
  #=================================
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Scheme: "internet-facing"
      Name: !Sub ${ALBName}-alb
      IpAddressType: !Ref IpAddressType
      Subnets:
        - !ImportValue lecture10-clf-PublicSubnet1id
        - !ImportValue lecture10-clf-PublicSubnet2id
      SecurityGroups:
        - !ImportValue "lecture10-sg-SG3-ALB"
      Tags:
        - Key: Name
          Value: !Sub ${ALBName}-alb
  #=================================
  # ALBをターゲットグループに関連付け
  #================================= 
  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP    