AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an EC2 instance with a key pair"

Parameters:
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "Key Pair Name"
  
  InstanceTypeParameter:
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
  
  ProjectName:
    Type: String
    Description: Lecture10-CFn-EC2
  
  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: The AMI ID for the EC2 instance

  EC2InstanceVolumeSize:
    Type: String
    Default: "20"
  
  EC2InstanceVolumeType:
    Type: String
    Default: "gp2"

#-----------------------------------------------------------------------------
# IAM Role to access S3 Bucket
#-----------------------------------------------------------------------------
Resources: 
  S3AccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "IAMRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  AccessPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: "Allow"
          Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
              - s3:DeleteObject
              - s3:GetBucketLocation
          Resource: "arn:aws:s3:::*"
        - Effect: "Allow"
          Action: "*"
          Resource:
            - "arn:aws:s3:::<lecture10-cfn-bucket>"
            - "arn:aws:s3:::<lecture10-cfn-bucket>/*"
      Roles:
      - !Ref S3AccessRole
  
  S3AccessInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref S3AccessRole 

  # ------------------------------------------------------------
  #  EC2の作成
  # ------------------------------------------------------------   
  Lecture10EC2CFn:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref S3AccessInstanceProfile
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref EC2InstanceAMI
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue lecture10-CFn-PublicSubnet1id
          GroupSet:
            - !ImportValue "lecture10-sg-SG1-EC2"
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: !Ref EC2InstanceVolumeSize
            VolumeType: !Ref EC2InstanceVolumeType
      Tags:
        - Key: Name
          Value: !Ref ProjectName

# ------------------------------------------------------------
#  ElasticIPの作成&EC2にアタッチ
# ------------------------------------------------------------ 
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Lecture10EC2CFn
      EIP: !Ref ElasticIP

Outputs:
  InstanceId:
    Description: "The Instance ID"
    Value: !Ref Lecture10EC2CFn
    Export:
      Name: "Lecture10-EC2CFn"
  InstancePublicIp:
    Description: "The public IP address of the EC2 instance"
    Value: !GetAtt "Lecture10EC2CFn.PublicIp"
    Export:
      Name: "Lecture10-public-IP-CFn"
