AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance with a key pair

Parameters:
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "Key Pair Name"
  
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
  
  ProjectName:
    Type: String
    Description: Lecture10-clf-EC2

  EC2InstanceVolumeSize:
    Type: String
    Default: "20"
  
  EC2InstanceVolumeType:
    Type: String
    Default: "gp2"
  
  EC2InstanceAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
    Description: The AMI ID for the EC2 instance

Resources:
  
  # ------------------------------------------------------------
  #  EC2の作成
  # ------------------------------------------------------------   
  Lecture10EC2clf:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: !Ref EC2InstanceVolumeSize
            VolumeType: !Ref EC2InstanceVolumeType
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref EC2InstanceAMI
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !ImportValue lecture10-clf-PublicSubnet1id
          GroupSet:
            - !ImportValue "lecture10-sg-SG1-EC2"
      Tags:
        - Key: Name
          Value: !Ref ProjectName
      
  # ------------------------------------------------------------
  #  ElasticIPの作成&EC2にアタッチ
  # ------------------------------------------------------------ 
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref Lecture10EC2clf
      EIP: !Ref ElasticIP

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref Lecture10EC2clf
    Export:
      Name: Lecture10-EC2clf

  InstancePublicIp:
    Description: The public IP address of the EC2 instance
    Value: !GetAtt Lecture10EC2clf.PublicIp